### ISSUE TITLE
Windows build @keyup.enter not working

### ISSUE THREAD

**Issue by joejarlett** [wailsapp/todo#10]
Hi,
When running in the browser, the item @keyup.enter works
in the wails build exe the item @keyup.enter doesn't work

I presume this is a fault of Vue and the webview browser implemented.
Is there any control over this?

Many thanks

**Comment by joejarlett** [comment]
I can see the same lack of functionality appears in IE11.
Will this mean that I won't be able to use @keyup.enter for windows builds?

Many thanks

**Comment by leaanthony** [comment]
That's correct. The v1 windowing library is limited to IE11 currently. The v2 windowing library is currently being developed with Mac and Linux almost finished. We will be starting on Windows shortly and are targeting WebView2 - which is WebKit, so these sorts of issues will go away!
