### ISSUE TITLE
window.external.invoke is not a function

### ISSUE THREAD

**Issue by npolizotis** [wailsapp/todo#7]
I cloned the repo

1.  Did an cd frontend && npm install
2.  wails serve
3.  cd frontend && npm run serve

I am getting a blank page and a console message
"window.external.invoke is not a function"
The minimal Vue example is working fine so the issue must be related to this app.

Mac OSX 10.15.6
Wails v1.8.0

Any idea 
thanks

**Comment by leaanthony** [comment]
Thanks for reporting this. The Todo app is really quite old (pre v1) so
there's a good chance it's broken. Try updating the Wails version in go.mod
to the latest version.

**Comment by npolizotis** [comment]
Thanks @leaanthony that did the trick. 
BTW really cool project.

thank you

**Comment by leaanthony** [comment]
Ah awesome! And thanks for the kind words!
